# Generated by Django 5.0.1 on 2024-02-21 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_lite', '0002_alter_rsvp_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['-date_of_rsvp']},
        ),
    ]
